FROM openjdk:8
MAINTAINER nakami 1050657124@qq.com

COPY build/libs/re-user-provider-1.0-SNAPSHOT.jar /re-user-provider-1.0-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/re-user-provider-1.0-SNAPSHOT.jar"]