apiVersion: apps/v1
#创建类型为Deployment
kind: Deployment
#Deployment的名字
metadata:
  name: user-provider
spec:
  selector:
    matchLabels:
      app: user-provider
#Number of desired pods. This is a pointer to distinguish between explicit
#zero and not specified. Defaults to 1
  replicas: 2
  template:
    #pod name and labels
    metadata:
      labels:
        app: user-provider
    spec:
      containers:
        - name: user-provider
          image: registry.cn-qingdao.aliyuncs.com/namimono/recloud-re-user-provider:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8092

---
apiVersion: v1
kind: Service
metadata:
  name: user-provider
  labels:
    svc: user-provider
spec:
  ports:
    - port: 8092
      targetPort: 8092
      protocol: TCP
  selector:
    app: user-provider
---

apiVersion: v1
kind: Endpoints
metadata:
  name: nacos-svc
subsets:
  - addresses:
      - ip: 192.168.56.101
    ports:
      - port: 8848